"""add performance score table

Revision ID: performance_score_001
Revises: 
Create Date: 2025-10-24 00:37:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'performance_score_001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('performance_scores',
    sa.Column('portfolio_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, comment='AI performance rating (0-100)'),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('rule_violations', sa.Integer(), nullable=False, comment='Игнорирование правил/уроков'),
    sa.Column('last_change_reason', sa.Text(), nullable=True, comment='Причина последнего изменения'),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_performance_scores_id'), 'performance_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_performance_scores_id'), table_name='performance_scores')
    op.drop_table('performance_scores')
    # ### end Alembic commands ###





