"""add performance log table

Revision ID: performance_log_001
Revises: futures_001
Create Date: 2025-10-25 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'performance_log_001'
down_revision: Union[str, None] = 'futures_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('performance_logs',
    sa.Column('ai_decision_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('portfolio_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('analysis_quality', sa.Integer(), nullable=False, comment='Quality of market analysis (1-10)'),
    sa.Column('decision_appropriateness', sa.Integer(), nullable=False, comment='Was decision appropriate? (1-10)'),
    sa.Column('risk_management', sa.Integer(), nullable=False, comment='Risk management score (1-10)'),
    sa.Column('overall_score', sa.Integer(), nullable=False, comment='Overall performance score (1-10)'),
    sa.Column('confidence_assessment', sa.Text(), nullable=True, comment='appropriate/overconfident/underconfident'),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Identified strengths'),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Identified weaknesses'),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Recommendations for improvement'),
    sa.Column('pattern_identified', sa.Text(), nullable=True, comment='Trading pattern identified'),
    sa.Column('summary', sa.Text(), nullable=True, comment='2-sentence assessment'),
    sa.Column('outcome_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Actual P&L if trade closed'),
    sa.Column('outcome_duration_hours', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Trade duration in hours'),
    sa.Column('outcome_profitable', sa.Integer(), nullable=True, comment='1=profitable, 0=loss, NULL=pending'),
    sa.Column('gpt_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full GPT response'),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_decision_id'], ['ai_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_logs_id'), 'performance_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_performance_logs_id'), table_name='performance_logs')
    op.drop_table('performance_logs')
    # ### end Alembic commands ###

